export CC=/run/current-system/sw/bin/clang
export CXX=/run/current-system/sw/bin/clang++
alias ls='ls --color=auto'
alias hx='helix'
#alias nvim='neovide'
export VISUAL="helix"
# export PATH="$HOME/zig-bootstrap/out/zig-x86_64-linux-gnu-native/bin:$PATH"
export PATH="$HOME/zig:$PATH"
export PATH="$HOME/zls/zig-out/bin:$PATH"
export PATH=$PATH:/home/nobu/.spicetify
export PATH="$HOME/.local/bin:$PATH"
export PATH="$HOME/Odin:$PATH"
export PATH="$HOME/ols:$PATH"
export DEBUGINFOD_URLS="https://debuginfod.archlinux.org"
export ODIN_ROOT="$HOME/Odin"
export VULKAN_SDK="/nix/store/nzz1vdvyp3b00gvc6hq48g2z5yml9zjx-vulkan-headers-1.3.249:$VULKAN_SDK"
export VULKAN_SDK="/nix/store/hrvx0baps9xhfzb2lv71di4hbqvcr7fz-vulkan-loader-1.3.249:$VULKAN_SDK"
export VULKAN_SDK="/nix/store/kinq12hayd004zfwmndfif158m7hd8fp-vulkan-validation-layers-1.3.249:$VULKAN_SDK"
export VULKAN_SDK="/nix/store/17za1lldv8jxgfa493n5d7kjhpirx46r-vulkan-validation-layers-1.3.249-headers:$VULKAN_SDK"
export VULKAN_SDK="/nix/store/76zm8yzdyd2hvwrja38c0s2fngxxdbn0-vulkan-extension-layer-1.3.248:$VULKAN_SDK"
