ln -s ~/dotfiles/.config/i3 ~/.config/i3
ln -s ~/dotfiles/.config/alacritty ~/.config/alacritty
ln -s ~/dotfiles/.config/polybar ~/.config/polybar
ln -s ~/dotfiles/.config/rofi ~/.config/rofi
ln -s ~/dotfiles/.config/dunst ~/.config/dunst
ln -s ~/dotfiles/.config/nvim ~/.config/nvim
ln -s ~/dotfiles/.config/tmux ~/.config/tmux
ln -s ~/dotfiles/.config/gtk-4.0 ~/.config/gtk-4.0
ln -s ~/dotfiles/.config/gtk-3.0 ~/.config/gtk-3.0
ln -s ~/dotfiles/.config/gtk-2.0 ~/.config/gtk-2.0
ln -s ~/dotfiles/.doom.d ~/.config/doom
