#!/usr/bin/env bash

selected=$(find ~/projects -mindepth 1 -maxdepth 1 -type d | fzf)

if [[ -z "$selected" ]]; then
    exit 0
fi

selected_name=$(basename "$selected" | tr . _)
tmux_running=$(pgrep tmux)

switch_to() {
    if [[ -z $TMUX ]]; then
        tmux attach-session -t=$1
    else
        tmux switch-client -t=$1
    fi
}

hydrate() {
    if [ -z $selected/.tmux-ready ]; then
        return
    fi

    tmux send-keys -t $selected_name "./.tmux-ready" c-M
}

# no tmux currently running, or tmux running, just not in this terminal
if tmux has-session -t="$selected_name"; then
    switch_to
else
    tmux new-session -ds $selected_name -c $selected
    switch_to

    # tmux send-keys -t $selected_name "ready-tmux"
fi
