import = ["/home/nobu/.config/alacritty/dracula.toml"]

[cursor.style]
shape = "Beam"

[font]
size = 14.0

[font.normal]
family = "FiraMono Nerd Font"

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "Return"
mods = "Control|Shift"

[shell]
program = "/bin/zsh"

[window]
decorations = "full"
dynamic_padding = true
opacity = 0.95

[window.padding]
x = 6
y = 5
