theme = "dracula"

[editor]
line-number = "absolute"
mouse = false
cursorline = true
bufferline = "always"
completion-replace = true

[editor.cursor-shape]
insert = "bar"
normal = "underline"
select = "block"

[editor.file-picker]
hidden = false

[editor.lsp]
display-messages = true
display-inlay-hints = true

[editor.statusline]
left = ["mode", "file-name", "file-modification-indicator"]
center = ["version-control"]
right = ["diagnostics", "workspace-diagnostics", "position"]


