theme = "tokyonight_transparent"

[editor]
line-number = "absolute"
mouse = false
cursorline = true
bufferline = "always"
completion-replace = false
completion-trigger-len = 2

[editor.cursor-shape]
insert = "bar"
normal = "underline"
select = "block"

[editor.file-picker]
hidden = false

[editor.lsp]
display-messages = true
display-inlay-hints = true

[editor.statusline]
left = ["mode", "file-name", "file-modification-indicator"]
center = ["version-control"]
right = ["diagnostics", "workspace-diagnostics", "position"]

[editor.soft-wrap]
enable = true

[keys.normal]
C-n = ":n" # open new scrath buffer
C-a = "code_action" # shows code actions
C-q = ":bc" # close current buffer
